services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - LOKI_PUSH_URL=${LOKI_PUSH_URL}
      - LOKI_USER_ID=${LOKI_USER_ID}
      - LOKI_API_TOKEN=${LOKI_API_TOKEN}

      - PROMETHEUS_REMOTE_WRITE_URL=${PROMETHEUS_REMOTE_WRITE_URL}
      - PROM_USER_ID=${PROM_USER_ID}
      - PROM_API_TOKEN=${PROM_API_TOKEN}

      - SPRING_BOOT_HOST=${SPRING_BOOT_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
    restart: unless-stopped